# Generated by Django 5.1.3 on 2024-12-07 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_fitness_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="fitness_goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weight_loss", "Weight Loss"),
                    ("muscle_gain", "Muscle Gain"),
                    ("maintenance", "Body Maintenance"),
                    ("diebetic", "Diet Supervision"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
