# Generated by Django 5.1.3 on 2024-12-25 16:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meallog",
            name="name",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "meal_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nutrition.mealtype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MealPlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.1)]
                    ),
                ),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nutrition.fooditem",
                    ),
                ),
                (
                    "meal_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="nutrition.mealplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NutritionGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("weight_loss", "Weight Loss"),
                            ("weight_gain", "Weight Gain"),
                            ("muscle_gain", "Muscle Gain"),
                            ("maintenance", "Weight Maintenance"),
                            ("performance", "Athletic Performance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sedentary"),
                            ("light", "Light Activity"),
                            ("moderate", "Moderate Activity"),
                            ("very_active", "Very Active"),
                            ("extra_active", "Extra Active"),
                        ],
                        max_length=20,
                    ),
                ),
                ("daily_calorie_target", models.IntegerField()),
                (
                    "protein_target",
                    models.FloatField(help_text="Grams of protein per day"),
                ),
                (
                    "carbohydrate_target",
                    models.FloatField(help_text="Grams of carbohydrates per day"),
                ),
                ("fat_target", models.FloatField(help_text="Grams of fat per day")),
                ("height", models.FloatField(help_text="Height in centimeters")),
                (
                    "current_weight",
                    models.FloatField(help_text="Current weight in kilograms"),
                ),
                (
                    "target_weight",
                    models.FloatField(help_text="Target weight in kilograms"),
                ),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
